---
- name: Template Demo
  hosts: localhost
  gather_facts: false

  vars:
    my_var: "Secret Data"

  tasks:

    - name: Render Template
      ansible.builtin.set_fact:
        my_example: "{{ lookup('ansible.builtin.template', 'example.json.j2') }}"

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ my_example }}"
